version: '3.4'
services:
  webapp:
    image: dockerspa
    container_name: backend
    ports:
      - "7143:7143"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:7143;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=admin@123
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    networks:   
        - dockerspanetwork
    volumes:
      - ~/.aspnet/https:/https:ro
      - ~/Projects/DockerSPAProject/DockerSPAProject/bin/Release/net6.0/publish:/app

  sqldb:
    #image: "mcr.microsoft.com/mssql/server"
    image: "mcr.microsoft.com/azure-sql-edge"
    environment:
          SA_PASSWORD: "Admin@123"
          ACCEPT_EULA: "Y"
    ports:
         - "1433:1433"
    networks:
        - dockerspanetwork
    volumes:
        - backup:/var/opt/mssql/backups
        - sqlserver:/var/opt/sqlserver
        - mssql:/var/opt/mssql

  frontapp:
    image: front
    container_name: frontapp
    ports:
        - "4200:4200"
    networks:
        - dockerspanetwork
        

networks:
    dockerspanetwork:


volumes:
  backup:
  sqlserver:
  mssql:

#dotnet dev-certs https -ep ${home}\.aspnet\https\aspnetapp.pfx -p admin@123   >> use this command for create trust certificate

