version: '3.4'

services:
  webapp:
    image: dockerspa
    container_name: backend
    ports:
      - "7143:7143"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:7143;http://+:5000
      - ASPNETCORE_Kestrel__Certificates__Default__Password=admin@123
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ~/.aspnet/https:/https:ro
    networks:
        - dockerspanetwork

  sqldb:
    container_name: sqlserver
    image: "mcr.microsoft.com/azure-sql-edge"
    environment:
          SA_PASSWORD: "Sudo@123"
          ACCEPT_EULA: "Y"
    ports:
         - "1433:1433"
    networks:
        - dockerspanetwork

networks:
    dockerspanetwork: